// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB1;

#nullable disable

namespace WEB1.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231024124837_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB1.Models.Clients", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneNumber");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            PhoneNumber = "0971565481",
                            FirstName = "Denys",
                            LastName = "Petrushchenko",
                            MiddleName = "Serhiyovych"
                        },
                        new
                        {
                            PhoneNumber = "0668910456",
                            FirstName = "Kyrylo",
                            LastName = "Kalushenko",
                            MiddleName = "Volodymyrovich"
                        },
                        new
                        {
                            PhoneNumber = "0937842857",
                            FirstName = "Mykola",
                            LastName = "Pron",
                            MiddleName = "Victorych"
                        });
                });

            modelBuilder.Entity("WEB1.Models.Worker", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Type_of_Worker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Worker_Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            ID = "389d2f71-7d1f-421a-a630-8c38a67615a5",
                            FirstName = "Mykhailo",
                            LastName = "Hlevatsky",
                            MiddleName = "Andriiovych",
                            Worker_Phone_Number = "0989381314"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
